#!/usr/bin/env bash
# build.sh — assemble the self-contained MV3 extension package.
#
# There is no bundler: the popup is plain ESM. All this script does is (1) build
# the repo-root `sigil-wasm` crate to a browser-ESM wasm-bindgen package and (2)
# copy the wasm bindings + the PROVEN, framework-free JS helpers into
# `extension/vendor/` so `extension/` can be loaded directly by the browser as an
# unpacked extension.
#
# Everything it writes (vendor/) is a BUILD ARTIFACT — gitignored, never
# committed. The extension SOURCE is manifest.json + src/.
#
# Pre-audit / UNAUDITED / DEV build. Do NOT store real 2FA secrets.
set -euo pipefail

# Pin the toolchain path exactly like the rest of the repo (macOS arm64).
export PATH="$HOME/.rustup/toolchains/stable-aarch64-apple-darwin/bin:$HOME/.cargo/bin:/opt/homebrew/bin:$PATH"

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$HERE/.." && pwd)"
WASM_SRC="$REPO_ROOT/sigil-wasm"
VENDOR="$HERE/vendor"

echo "== building the sigil-wasm browser package (wasm-pack --target web) =="
# The repo-root builder is the single source of truth for how the wasm is built
# (it pins wasm-pack 0.13.1, matching the `wasm-bindgen = \"=0.2.100\"` pin).
"$WASM_SRC/build-wasm.sh"

echo
echo "== vendoring into $VENDOR =="
rm -rf "$VENDOR"
mkdir -p "$VENDOR"

# (1) The wasm-bindgen browser ESM bindings. `sigil_wasm.js` resolves the wasm
#     next to itself by default; the popup passes an explicit
#     chrome.runtime.getURL() anyway, so both live in the same directory.
cp "$WASM_SRC/pkg-web/sigil_wasm.js"      "$VENDOR/"
cp "$WASM_SRC/pkg-web/sigil_wasm_bg.wasm" "$VENDOR/"
cp "$WASM_SRC/pkg-web/sigil_wasm.d.ts"    "$VENDOR/"

# (2) The proven, wasm-agnostic JS helpers — copied verbatim, NOT reimplemented.
#     totp-migration.mjs imports "./totp-vault.mjs", device-auth.mjs imports
#     "./sync.mjs", sharing.mjs imports both "./device-auth.mjs" and
#     "./totp-vault.mjs", recovery.mjs imports "./device-auth.mjs" and
#     "./sharing.mjs", and entitlement.mjs imports "./device-auth.mjs" — so all
#     EIGHT must stay siblings. (clock-skew.mjs imports NOTHING: it reads one
#     HTTP response header and does no crypto, no auth and no storage.)
cp "$WASM_SRC/totp-vault.mjs"     "$VENDOR/"
cp "$WASM_SRC/totp-migration.mjs" "$VENDOR/"
cp "$WASM_SRC/sync.mjs"           "$VENDOR/"
cp "$WASM_SRC/device-auth.mjs"    "$VENDOR/"
cp "$WASM_SRC/sharing.mjs"        "$VENDOR/"
cp "$WASM_SRC/recovery.mjs"       "$VENDOR/"
cp "$WASM_SRC/entitlement.mjs"    "$VENDOR/"
cp "$WASM_SRC/clock-skew.mjs"     "$VENDOR/"

# A provenance stamp so a stale vendor/ is obvious.
cat > "$VENDOR/BUILD-INFO.txt" <<EOF
Generated by extension/build.sh — DO NOT EDIT, DO NOT COMMIT.
source:  $WASM_SRC (repo-root sigil-wasm crate + JS helpers)
commit:  $(git -C "$REPO_ROOT" rev-parse --short HEAD 2>/dev/null || echo unknown)
built:   $(date -u +%Y-%m-%dT%H:%M:%SZ)
EOF

echo
echo "Extension package ready: $HERE"
ls -la "$VENDOR"
echo
echo "Load it unpacked:  chrome://extensions -> Developer mode -> Load unpacked -> $HERE"
echo "Headless proof:    corepack pnpm -C \"$HERE\" test"
