// @sigil/wasm — the workspace loader package the webapp imports.
//
// It re-exports two things behind one typed surface:
//   1. the BUNDLER-target wasm exports generated by ./build.sh into ./pkg
//      (seal/open, hybrid_*, totp/hotp/format_code, …); and
//   2. the PROVEN, wasm-agnostic JS helpers that live next to the Rust crate at
//      the repo root (totp-vault / sync / totp-migration). Those are imported by
//      RELATIVE PATH — the SAME tested source the CLI-interop tests exercise, not
//      a rewrite. They take the wasm binding as an injected object.
//
// The `./pkg/sigil_wasm.js` entry instantiates the wasm on import via the
// bundler's asyncWebAssembly support (Next.js: experiments.asyncWebAssembly).
// Under that mode the importing module graph is async, so by the time these
// bindings are reachable the wasm is live. `initWasm()` gives callers a single
// awaitable that resolves to the ready binding object.
//
// Pre-audit / UNAUDITED demo of the wasm-pure sigil-core. Do NOT protect real
// secrets.

import * as wasm from "./pkg/sigil_wasm.js";

// The raw wasm surface (also spread as named re-exports below for ergonomics).
export const {
  seal_record,
  open_record,
  seal_to_container,
  open_container,
  hybrid_x25519_public,
  hybrid_mlkem_encaps_key,
  hybrid_seal_to_container,
  hybrid_open_container,
  totp,
  hotp,
  format_code,
  nonce_len,
  recommended_salt_len,
  version,
} = wasm;

/**
 * Resolve to the ready wasm binding object. With the bundler target the wasm is
 * already instantiated by the time this module evaluates, so this is a thin
 * awaitable wrapper that gives every caller a uniform readiness point (and the
 * exact object shape the injected-`wasm` helpers below expect).
 */
export async function initWasm() {
  return wasm;
}

// The proven helpers — SAME source as the repo-root crate's Node interop tests.
export * from "../../../sigil-wasm/totp-vault.mjs";
export * from "../../../sigil-wasm/sync.mjs";
export * from "../../../sigil-wasm/totp-migration.mjs";
