// @sigil/wasm — the workspace loader package the webapp imports.
//
// It re-exports two things behind one typed surface:
//   1. the BUNDLER-target wasm exports generated by ./build.sh into ./pkg
//      (seal/open, hybrid_*, totp/hotp/format_code, …); and
//   2. the PROVEN, wasm-agnostic JS helpers that live next to the Rust crate at
//      the repo root (totp-vault / sync / totp-migration). Those are imported by
//      RELATIVE PATH — the SAME tested source the CLI-interop tests exercise, not
//      a rewrite. They take the wasm binding as an injected object.
//
// The `./pkg/sigil_wasm.js` entry instantiates the wasm on import via the
// bundler's asyncWebAssembly support (Next.js: experiments.asyncWebAssembly).
// Under that mode the importing module graph is async, so by the time these
// bindings are reachable the wasm is live. `initWasm()` gives callers a single
// awaitable that resolves to the ready binding object.
//
// Pre-audit / UNAUDITED demo of the wasm-pure sigil-core. Do NOT protect real
// secrets.

import * as wasm from "./pkg/sigil_wasm.js";

// The raw wasm surface (also spread as named re-exports below for ergonomics).
export const {
  seal_record,
  open_record,
  seal_to_container,
  open_container,
  // ⭐ The NO-DOWNGRADE RATCHET for JS re-seals (Phase 59 fix round). Without
  // these re-exported here, `ratchetParams` — which is handed this module
  // namespace as its `wasm` — would call an undefined function and every browser
  // re-seal would silently fall back to this build's own (weaker) defaults.
  container_params,
  reseal_params,
  ed25519_public_key,
  ed25519_sign,
  ed25519_verify,
  hybrid_x25519_public,
  hybrid_mlkem_encaps_key,
  hybrid_seal_to_container,
  hybrid_open_container,
  // ⭐ THE AUTHENTICATED vault-key envelope (Phase 60). Without these three
  // re-exported HERE, `sharing.mjs` — which is handed this module namespace as
  // its `wasm` — would call undefined functions and EVERY browser share, rotate,
  // accept, recovery-cover and restore would throw at runtime. That is exactly
  // the trap Phase 56 fell into with `recovery_*`: typed in index.d.ts, absent
  // here. The .d.ts declarations are a SEPARATE hole and are closed too.
  vault_key_wrap_aad,
  hybrid_auth_seal_to_container,
  hybrid_auth_open_container,
  // THE RECOVERY KIT codec + HKDF derivation (Phase 54). These were declared in
  // index.d.ts but never re-exported here, so `recovery.mjs` — which is handed
  // this module namespace as its `wasm` — called an undefined function the first
  // time a browser client tried to generate a kit.
  recovery_encode,
  recovery_decode,
  recovery_derive_ed25519_seed,
  recovery_derive_x25519_secret,
  recovery_derive_mlkem_seed,
  recovery_format,
  totp,
  hotp,
  format_code,
  nonce_len,
  recommended_salt_len,
  version,
} = wasm;

/**
 * Resolve to the ready wasm binding object. With the bundler target the wasm is
 * already instantiated by the time this module evaluates, so this is a thin
 * awaitable wrapper that gives every caller a uniform readiness point (and the
 * exact object shape the injected-`wasm` helpers below expect).
 */
export async function initWasm() {
  return wasm;
}

// The proven helpers — SAME source as the repo-root crate's Node interop tests.
export * from "../../../sigil-wasm/totp-vault.mjs";
export * from "../../../sigil-wasm/sync.mjs";
export * from "../../../sigil-wasm/totp-migration.mjs";
// The client half of sigild's multi-device auth (contract v3 + enrollment). Same
// source as sigil-wasm/test/device-auth-interop.mjs, which proves it against a
// live server.
export * from "../../../sigil-wasm/device-auth.mjs";
// Device-to-device vault sharing: hybrid key publish/fetch, vault-key wrap/unwrap
// and the opaque envelope relay. Same source as
// sigil-wasm/test/sharing-interop.mjs, which proves it BOTH ways against the real
// `sigil` CLI through a live server.
export * from "../../../sigil-wasm/sharing.mjs";
// THE RECOVERY KIT (Phase 54): a paper credential that is an ordinary member
// device. Same source as sigil-wasm/test/recovery-interop.mjs, which proves it
// BOTH ways against the real `sigil` CLI through a live server.
//
// ⚠️ A recovery code and every seed derived from it are SECRETS. A UI must
// render a code ONCE and never write it to localStorage, a URL, an analytics
// event or a log line.
export * from "../../../sigil-wasm/recovery.mjs";
// PASSKEY-PROTECTED LOCAL CONTAINERS (ADR 0046): a second AT-REST factor for the
// two sealed containers. It changes NOTHING on the wire — request auth is still
// the classical Ed25519 contract-v3 signature and `sigild` never learns this
// exists. The break-glass is the EXISTING ADR 0042 recovery sheet, so there is no
// second paper artifact and no server involvement.
//
// ⚠️ Re-exported HERE **and** declared in index.d.ts. Phase 56 proved those are
// two separate holes: `recovery_*` was typed but never re-exported, so every
// browser recovery call threw at runtime while `tsc` stayed clean.
export * from "../../../sigil-wasm/passkey.mjs";
// ENTITLEMENT (Phase 55 server side, read here): sigild's warning headers, the
// additive `entitlement` block on GET /v1/billing/subscription, and the
// machine-readable 402. Reading it is how a client can say the TRUE thing —
// writes may be refused, reads and same-account key recovery never are.
export * from "../../../sigil-wasm/entitlement.mjs";
